### ISSUE TITLE
Failing test in DefaultGCEExchangeFacadeTest

### ISSUE THREAD

**Issue by wrabbit23** [CoreMedia/coremedia-globallink-connect-integration#59]
apps/workflow-server/gcc-workflow-server-facade/gcc-restclient-facade-default/src/test/java/com/coremedia/labs/translation/gcc/facade/def/DefaultGCExchangeFacadeTest.java

There are two tests here: 
#169 (Test for successful submission)
#204 (Correctly deal with communication errors) 

That fail when running in US time zone CST with the following error:

java.lang.IllegalArgumentException: DueDate must be after current date

I believe it is an issue with time zone handling.

**Comment by mmichaelis** [comment]
To reproduce:

```shell
mvn test -pl :gcc-restclient-facade-default -Duser.timezone="America/Chicago"
```

Failures are:

```text
[ERROR] com.coremedia.labs.translation.gcc.facade.def.DefaultGCExchangeFacadeTest$SubmitSubmission.happyPath(TestInfo) -- Time elapsed: 0.024 s <<< ERROR!
java.lang.IllegalArgumentException: DueDate must be after current date
        at org.gs4tr.gcc.restclient.request.SubmissionSubmitRequest.<init>(SubmissionSubmitRequest.java:72)
        at com.coremedia.labs.translation.gcc.facade.def.DefaultGCExchangeFacade.submitSubmission(DefaultGCExchangeFacade.java:165)
        at com.coremedia.labs.translation.gcc.facade.def.DefaultGCExchangeFacadeTest$SubmitSubmission.happyPath(DefaultGCExchangeFacadeTest.java:189)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
```

and

```text
[ERROR] com.coremedia.labs.translation.gcc.facade.def.DefaultGCExchangeFacadeTest$SubmitSubmission.dealWithCommunicationExceptions(TestInfo) -- Time elapsed: 0.007 s <<< FAILURE!
java.lang.AssertionError:

Expecting actual throwable to be an instance of:
  com.coremedia.labs.translation.gcc.facade.GCFacadeCommunicationException
but was:
  java.lang.IllegalArgumentException: DueDate must be after current date
        at org.gs4tr.gcc.restclient.request.SubmissionSubmitRequest.<init>(SubmissionSubmitRequest.java:72)
        at com.coremedia.labs.translation.gcc.facade.def.DefaultGCExchangeFacade.submitSubmission(DefaultGCExchangeFacade.java:165)
        at com.coremedia.labs.translation.gcc.facade.def.DefaultGCExchangeFacadeTest$SubmitSubmission.lambda$dealWithCommunicationExceptions$0(DefaultGCExchangeFacadeTest.java:220)
        ...(86 remaining lines not displayed - this can be changed with Assertions.setMaxStackTraceElementsDisplayed)
        at com.coremedia.labs.translation.gcc.facade.def.DefaultGCExchangeFacadeTest$SubmitSubmission.dealWithCommunicationExceptions(DefaultGCExchangeFacadeTest.java:221)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
```

**Comment by mmichaelis** [comment]
As it seems, there may be an issue within the GCC REST API or a misunderstanding. We assumed, that the time to be provided as due date is in UTC (and we transform it accordingly in `GCUtil`). The check within the GCC REST API (version 3.1.3), though, is as follows:

```java
    } else if (dueDate.compareTo(new Date()) < 0) {
      throw new IllegalArgumentException("DueDate must be after current date");
```

which would fail, for example, today comparing:

* Due Date: `Thu Feb 15 04:38:28 CET 2024`
* with current date (via `new Date()`): `Thu Feb 15 09:40:31 CET 2024`.

**Comment by mmichaelis** [comment]
Created issue:

* translations-com/globallink-connect-cloud-api-java#17
